spring:
  datasource:    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: 1qaz2wsx
    
server:  port: 8443
  ssl:    key-store: file:/taco-cloud/mykeys.jks
    key-store-password: letmein
    key-password: letmein