spring:
  datasource:    url: jdbc:mysql://localhost:3306/tacocloud?serverTimezone=UTC
    username: root
    password: 1qaz2wsx
    
server:  port: 8443
  ssl:    key-store: file:C:\Users\Testerzy\eclipse-workspace\taco-cloud\mykeys.jks
    key-store-password: letmein
    key-password: letmein
    
taco:
  orders:
    pageSize: 10