spring:
  datasource:    url: jdbc:mysql://localhost:3306/tacocloud?serverTimezone=UTC
    username: root
    password: 1qaz2wsx
  jpa:    hibernate:      ddl-auto: update
  data:    rest:      base-path: /api
        
taco:
  orders:
    pageSize: 10